# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Femail')], max_length=1)),
            ],
            managers=[
                ('men', django.db.models.manager.Manager()),
            ],
        ),
    ]
