# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 22:18
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_author'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
    ]
