# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20170428_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Person',
        ),
    ]
